name: Tests

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check theme with gscan
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm test